apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiki-main

namePrefix: main-
nameSuffix: -main

labels:
  - pairs:
      app.kubernetes.io/environment: main
      app.kubernetes.io/instance: main

resources:
  - namespace.yml
  - ../../base

replicas:
  - name: public-wiki
    count: 3

images:
  - name: ghcr.io/42core-team/wiki
    newTag: main

patches:
  - target:
      kind: Ingress
      name: public-wiki-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: wiki.coregame.de
      - op: replace
        path: /spec/tls/0/hosts/0
        value: wiki.coregame.de
      - op: replace
        path: /spec/tls/0/secretName
        value: wiki-coregame-de-tls
