namePrefix: main-
namespace: wiki
labels:
  - pairs:
      app: public-wiki
      env: main
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
      name: public-wiki
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/42core-team/wiki:main
  - target:
      kind: Ingress
      name: public-wiki-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: wiki.coregame.de
      - op: replace
        path: /spec/tls/0/hosts/0
        value: wiki.coregame.de
      - op: replace
        path: /spec/tls/0/secretName
        value: wiki-coregame-de-tls
