apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-wiki-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com # will be patched in overlays
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: public-wiki
            port:
              number: 80
