apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-wiki-ingress
  labels:
    app.kubernetes.io/name: public-wiki
    app.kubernetes.io/component: web
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - example.com
    secretName: public-wiki-tls
  rules:
  - host: example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: public-wiki
            port:
              name: http
