apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-wiki-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - example.com # will be patched in overlays
    secretName: public-wiki-tls
  rules:
  - host: example.com # will be patched in overlays
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: public-wiki
            port:
              number: 80
