apiVersion: v1
kind: Service
metadata:
  name: public-wiki
  labels:
    app.kubernetes.io/name: public-wiki
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: public-wiki
    app.kubernetes.io/component: web
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
