apiVersion: v1
kind: Service
metadata:
  name: public-wiki
  namespace: wiki
  labels:
    app: public-wiki
spec:
  selector:
    app: public-wiki
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
