apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wiki-dev

namePrefix: dev-
nameSuffix: -dev

labels:
  - pairs:
      app.kubernetes.io/environment: dev
      app.kubernetes.io/instance: dev

resources:
  - namespace.yml
  - ../../base

replicas:
  - name: public-wiki
    count: 1

images:
  - name: ghcr.io/42core-team/wiki
    newTag: dev

patches:
  - target:
      kind: Ingress
      name: public-wiki-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.wiki.coregame.de
      - op: replace
        path: /spec/tls/0/hosts/0
        value: dev.wiki.coregame.de
      - op: replace
        path: /spec/tls/0/secretName
        value: dev-wiki-coregame-de-tls
