namePrefix: dev-
namespace: wiki
commonLabels:
  app: public-wiki
  env: dev

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: public-wiki
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: ghcr.io/42core-team/wiki:dev
  - target:
      kind: Ingress
      name: public-wiki-ingress
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.wiki.coregame.de
